version: '3.3'

services:
    proxy:
        image: nginx:stable-alpine
        container_name: camipass-proxy
        restart: always
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - ./letsencrypt:/data/letsencrypt/
            - ./nginx-h5bp/server-configs-nginx-master:/etc/nginx/
            - /home/manager/nginx-logs:/var/log/nginx/
            - /etc/letsencrypt:/etc/letsencrypt/
    mysql:
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        image: mysql:latest
        container_name: camipass-mysql
        hostname: camipass-mysql
        volumes:
            - /home/manager/camipass-mysql:/data/db
        env_file:
            - .env
        ports:
            - '3306'
        healthcheck:
            test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
            timeout: 20s
            retries: 10
    server:
        image: camipass/server
        container_name: camipass-server
        hostname: camipass-server
        restart: always
        build:
            context: ./camipass-server
            dockerfile: Dockerfile
        env_file:
            - .env
        depends_on:
            mysql:
                condition: service_healthy
        volumes:
            - /home/manager/camipass-upload:/usr/src/app/public/upload
    client:
        image: camipass/client
        container_name: camipass-client
        hostname: camipass-client
        restart: always
        env_file:
            - .env
        build:
            context: ./camipass-client
